from typing import Any, Dict, List, Optional, TypedDict


class GameState(TypedDict, total=False):
    """
    Central state container tracked across the 3-player relay and evaluation.
    """
    session_id: str
    team_name: str
    case_id: str
    case_file: str                  # Raw noisy case story (Player 1 only)
    ground_truth: Dict[str, Any]    # Answer key / expected solution
    leak_keywords: List[str]        # Words that indicate premature leak in Step 2

    # Step 1: Evidence Extraction
    user_1_prompt: str              # Player 1's instructions
    agent_1_output: str             # Facts extracted by Agent 1

    # Step 2: Timeline Reconstruction
    user_2_prompt: str              # Player 2's instructions
    agent_2_output: str             # Timeline generated by Agent 2
    leak_detected: bool             # Flagged if Agent 2 prematurely leaks killer
    leak_keywords_found: List[str]  # Keywords triggered

    # Step 3: Verdict & Formatting
    user_3_prompt: str              # Player 3's instructions
    raw_agent_3_output: str         # Raw LLM response from Agent 3
    final_verdict: Dict[str, Any]   # Parsed JSON: {culprit, method, clue}

    # Step 4: Objective Evaluation
    evaluation: Dict[str, Any]      # Rubric scores, expected vs actual diff, total score

    # Diagnostics
    error: Optional[str]            # Holds error details if any node encounters issues
